spring.application.name=springbootapp
spring.datasource.url=jdbc:mariadb://localhost:3306/springbootapp?serverTimezone=UTC
spring.datasource.username=springuser
spring.datasource.password=bish
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
